### PR TITLE
Skip pundit authorization for status action

### LINKED ISSUE #205: Tests fail for new project
Cool project!

I just cloned the repo and followed the installation instructions. I get two test failures right out of the box:

Screen Shot 2020-05-17 at 3 49 28 PM

* **Version**: which version of this repo do you have?
v1.1.2 (Latest commit 3c4bffd)

* **Ruby Version**: which version of ruby do you have?
ruby 2.6.3p62

* **Environment**: in which env is happening?
Dev / localhost

* **Rails Stacktrace**: this can be found in the `log/development.log` or `log/test.log`, if this is applicable.

```
  [1m[35m (0.4ms)[0m  [1m[34mSELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1[0m  [["key", "schema_sha1"]]
  [1m[35m (0.6ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.6ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "keneth@zemlakwintheiser.info"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "5797fdd0-b429-49de-8ce4-cb556fd10ade"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.5ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "keneth@zemlakwintheiser.info"], ["encrypted_password", "$2a$04$jvBzu624rOHH4wWWnpr6qe3zNHdl0yZe0VFpAiFTcZqhXghXoTEaW"], ["username", "aleta.ullrich"], ["created_at", "2020-05-17 22:54:18.118766"], ["updated_at", "2020-05-17 22:54:18.118766"], ["uid", "keneth@zemlakwintheiser.info"]]
  [1m[35m (0.3ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "keneth@zemlakwintheiser.info"], ["id", 75], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:18.179090"], ["tokens", "\"{\\\"Olpz5pIW-wZqmDD0992x4w\\\":{\\\"token\\\":\\\"$2a$10$awWCB7bziN3iz5Y30MGwBuexw1cZDh/zVCz/tkMI3n65OVCJIOs3C\\\",\\\"expiry\\\":1652828058,\\\"updated_at\\\":\\\"2020-05-17 22:54:18 UTC\\\"}}\""], ["id", 75]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started GET "/api/v1/user/profile" for 127.0.0.1 at 2020-05-17 15:54:18 -0700
Processing by Api::V1::UsersController#profile as JSON
  Parameters: {"user"=>{}}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "keneth@zemlakwintheiser.info"], ["LIMIT", 1]]
  Rendering api/v1/users/show.json.jbuilder
  Rendered api/v1/users/_info.json.jbuilder (Duration: 0.3ms | Allocations: 110)
  Rendered api/v1/users/show.json.jbuilder (Duration: 1.4ms | Allocations: 748)
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 75], ["LIMIT", 1]]
Completed 200 OK in 69ms (Views: 4.9ms | ActiveRecord: 1.1ms | Allocations: 3753)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "monnie_nikolaus@lind.info"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "2c317595-a6cb-4e89-81ee-ea892481f5c2"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "monnie_nikolaus@lind.info"], ["encrypted_password", "$2a$04$pDukWdUWTZoPC1guEuJA1OkF27q21my2RVGRgi2Bh7ToW7jN8VO2i"], ["username", "granville.barrows"], ["created_at", "2020-05-17 22:54:18.287915"], ["updated_at", "2020-05-17 22:54:18.287915"], ["uid", "monnie_nikolaus@lind.info"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.4ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "monnie_nikolaus@lind.info"], ["id", 76], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:18.351122"], ["tokens", "\"{\\\"F6nHeH8zNU3Tc-bwn4zuqg\\\":{\\\"token\\\":\\\"$2a$10$.Eo2GsYZdzAY8OiFWtpHoudmxLZQlSwtFxH.YjEih4ZfMXsUKXUIu\\\",\\\"expiry\\\":1652828058,\\\"updated_at\\\":\\\"2020-05-17 22:54:18 UTC\\\"}}\""], ["id", 76]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started GET "/api/v1/user/profile" for 127.0.0.1 at 2020-05-17 15:54:18 -0700
Processing by Api::V1::UsersController#profile as JSON
  Parameters: {"user"=>{}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "monnie_nikolaus@lind.info"], ["LIMIT", 1]]
  Rendering api/v1/users/show.json.jbuilder
  Rendered api/v1/users/_info.json.jbuilder (Duration: 0.1ms | Allocations: 35)
  Rendered api/v1/users/show.json.jbuilder (Duration: 0.3ms | Allocations: 213)
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 76], ["LIMIT", 1]]
Completed 200 OK in 61ms (Views: 0.7ms | ActiveRecord: 0.9ms | Allocations: 1180)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
Started DELETE "/api/v1/users/sign_out" for 127.0.0.1 at 2020-05-17 15:54:18 -0700
Processing by Api::V1::SessionsController#destroy as JSON
  Parameters: {"session"=>{}}
Completed 404 Not Found in 1ms (Views: 0.2ms | ActiveRecord: 0.0ms | Allocations: 451)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "pasquale@steuber.name"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "b916963a-1975-4e7e-ad64-548bc70ed462"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "pasquale@steuber.name"], ["encrypted_password", "$2a$04$Ip9Q1RJVEYqmOJIPz5JJFOe92w6uITaJKAbKvJE40Q/G/tIHnCCkm"], ["username", "harley.nitzsche"], ["created_at", "2020-05-17 22:54:18.456526"], ["updated_at", "2020-05-17 22:54:18.456526"], ["uid", "pasquale@steuber.name"]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "pasquale@steuber.name"], ["id", 77], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:18.516673"], ["tokens", "\"{\\\"tt2c64Lw-VmQ9mCD5dD-Cg\\\":{\\\"token\\\":\\\"$2a$10$18snSqDo4tD4Bgm/QVkUFeveKbfy7cgkflKgZArf7l7sKavr3jkx.\\\",\\\"expiry\\\":1652828058,\\\"updated_at\\\":\\\"2020-05-17 22:54:18 UTC\\\"}}\""], ["id", 77]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 77], ["LIMIT", 1]]
Started DELETE "/api/v1/users/sign_out" for 127.0.0.1 at 2020-05-17 15:54:18 -0700
Processing by Api::V1::SessionsController#destroy as JSON
  Parameters: {"session"=>{}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "pasquale@steuber.name"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "pasquale@steuber.name"], ["id", 77], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.5ms)[0m  [1m[33mUPDATE "users" SET "tokens" = $1, "updated_at" = $2 WHERE "users"."id" = $3[0m  [["tokens", nil], ["updated_at", "2020-05-17 22:54:18.594514"], ["id", 77]]
  [1m[35m (0.4ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Completed 200 OK in 61ms (Views: 0.2ms | ActiveRecord: 1.9ms | Allocations: 1261)
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 77], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "kyle@oreilly.co"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "cd10d79f-77af-4a88-99c9-2c0b5f320758"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "kyle@oreilly.co"], ["encrypted_password", "$2a$04$D.Lw99l303bTUlCy/UZ9wep9RRPMM0kBgMQqkdscljQ4cgtd1xyk."], ["username", "eddie.schaefer"], ["created_at", "2020-05-17 22:54:18.604508"], ["updated_at", "2020-05-17 22:54:18.604508"], ["uid", "kyle@oreilly.co"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "kyle@oreilly.co"], ["id", 78], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:18.671125"], ["tokens", "\"{\\\"pCWXUK5eeoITAgzWb8bePg\\\":{\\\"token\\\":\\\"$2a$10$FN4/9azN4B0TxaTqRbOgb.vzwufHNIDfV.GXIMkjpFbhMKW646kHG\\\",\\\"expiry\\\":1652828058,\\\"updated_at\\\":\\\"2020-05-17 22:54:18 UTC\\\"}}\""], ["id", 78]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started DELETE "/api/v1/users/sign_out" for 127.0.0.1 at 2020-05-17 15:54:18 -0700
Processing by Api::V1::SessionsController#destroy as JSON
  Parameters: {"session"=>{}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "kyle@oreilly.co"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "kyle@oreilly.co"], ["id", 78], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.5ms)[0m  [1m[33mUPDATE "users" SET "tokens" = $1, "updated_at" = $2 WHERE "users"."id" = $3[0m  [["tokens", nil], ["updated_at", "2020-05-17 22:54:18.761421"], ["id", 78]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Completed 200 OK in 73ms (Views: 0.2ms | ActiveRecord: 1.8ms | Allocations: 1259)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT COUNT(*) FROM "users"[0m
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."provider" = $1 AND "users"."uid" IS NULL ORDER BY "users"."id" ASC LIMIT $2[0m  [["provider", "provider"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "a30323be-0968-4fed-b6f8-4ea0724d6045"], ["provider", "provider"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "provider", "uid") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"[0m  [["email", "keith@wunsch.org"], ["encrypted_password", "$2a$04$9e6HZao7n9hMgr11YaNkd.2WHJR1mBcsDdutGsxNZDUjC4/papzQ."], ["username", "pansy_schuster"], ["created_at", "2020-05-17 22:54:18.774789"], ["updated_at", "2020-05-17 22:54:18.774789"], ["provider", "provider"], ["uid", "a30323be-0968-4fed-b6f8-4ea0724d6045"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[34mSELECT COUNT(*) FROM "users"[0m
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "user@example.com"], ["provider", "provider"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "provider", "uid") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"[0m  [["email", "gabriella@okeefe.com"], ["encrypted_password", "$2a$04$w.uv/pEevmAXuH3NZdjEluIeiu/un870Fu31xT1KDfQdUj3BIdc7."], ["username", "venice.ziemann"], ["created_at", "2020-05-17 22:54:18.781662"], ["updated_at", "2020-05-17 22:54:18.781662"], ["provider", "provider"], ["uid", "user@example.com"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."provider" = $1 AND "users"."uid" = $2 ORDER BY "users"."id" ASC LIMIT $3[0m  [["provider", "provider"], ["uid", "user@example.com"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "milan.fritsch@goldnerward.io"], ["encrypted_password", "$2a$04$XtmBbsCTaegU1Ezmhe7r4.TajPvzyjeOU6MsAD.HgSTsKR48A1oTG"], ["username", "malcom"], ["created_at", "2020-05-17 22:54:18.790276"], ["updated_at", "2020-05-17 22:54:18.790276"], ["uid", "milan.fritsch@goldnerward.io"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "milan.fritsch@goldnerward.io"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "milan.fritsch@goldnerward.io"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "milan.fritsch@goldnerward.io"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "MILAN.FRITSCH@GOLDNERWARD.IO"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users"[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "milan.fritsch@goldnerward.io"], ["provider", "emaim"], ["LIMIT", 1]]
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", ""], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "a443f805-ce8e-48dc-9240-5d120b8c1488"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" IS NULL AND "users"."provider" = $1 LIMIT $2[0m  [["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "a443f805-ce8e-48dc-9240-5d120b8c1488"], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Create (0.4ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "julius@lynch.biz"], ["encrypted_password", "$2a$04$/igH4yE3LnVT4qQNwPWA5uA/Yx.GN6/LnJx5l3RcqnHYphBMZ02vy"], ["username", "jefferson"], ["created_at", "2020-05-17 22:54:18.818476"], ["updated_at", "2020-05-17 22:54:18.818476"], ["uid", "julius@lynch.biz"]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "julius@lynch.biz"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "julius@lynch.biz"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "julius@lynch.biz"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "julius@lynch.biz"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users"[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "julius@lynch.biz"], ["provider", "emaim"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "norma_konopelski@altenwerth.name"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "d16a3558-5105-4775-9a1a-a15779c663e8"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.4ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "norma_konopelski@altenwerth.name"], ["encrypted_password", "$2a$04$68gyUrmjVDNsGISXWYiwweKS/rNd1VdbLvxBM9gsqaQL5SutHy54u"], ["username", "estelle_schowalter"], ["created_at", "2020-05-17 22:54:18.835839"], ["updated_at", "2020-05-17 22:54:18.835839"], ["uid", "norma_konopelski@altenwerth.name"]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "orval@ryanspencer.biz"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "f5e37f65-7bac-457f-bcdb-f5eb907a0f7c"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "first_name", "last_name", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"[0m  [["email", "orval@ryanspencer.biz"], ["encrypted_password", "$2a$04$a3xO5qnQeVjc/BdYsk5aw.CGhNbkO0453BNTEOLXJihrmQI3xjqZ2"], ["first_name", "John"], ["last_name", "Doe"], ["username", "kristan"], ["created_at", "2020-05-17 22:54:18.843752"], ["updated_at", "2020-05-17 22:54:18.843752"], ["uid", "orval@ryanspencer.biz"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "willard_gorczany@ohara.net"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "b84161f5-bd7c-449c-82e9-6ff08e7b0760"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "willard_gorczany@ohara.net"], ["encrypted_password", "$2a$04$MDOKkgxPCtJuHn9ihz1P1.nV1Yi5ahj57cDOad3uHqLAWW1gt8kJy"], ["username", "francoise.wolf"], ["created_at", "2020-05-17 22:54:18.860823"], ["updated_at", "2020-05-17 22:54:18.860823"], ["uid", "willard_gorczany@ohara.net"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["reset_password_token", "c8de9019df5f5891c8b270d2ba062af9c3540578bcf44265d855cdfe108fb408"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "reset_password_token" = $1, "reset_password_sent_at" = $2, "updated_at" = $3 WHERE "users"."id" = $4[0m  [["reset_password_token", "c8de9019df5f5891c8b270d2ba062af9c3540578bcf44265d855cdfe108fb408"], ["reset_password_sent_at", "2020-05-17 22:54:18.962700"], ["updated_at", "2020-05-17 22:54:18.962909"], ["id", 85]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "willard_gorczany@ohara.net"], ["id", 85], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:19.022584"], ["tokens", "\"{\\\"PHRe6BgOnNZxkx8XJLCB9g\\\":{\\\"token\\\":\\\"$2a$10$UcyT9./Z4pUq7DTQuza00O9dTCD.n0m6dnnziQBg2a0aAi1noHR3O\\\",\\\"expiry\\\":1652828059,\\\"updated_at\\\":\\\"2020-05-17 22:54:18 UTC\\\"}}\""], ["id", 85]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started GET "/api/v1/users/password/edit?reset_password_token=[FILTERED]&redirect_url=http%3A%2F%2F127.0.0.1%3A3000" for 127.0.0.1 at 2020-05-17 15:54:19 -0700
Processing by Api::V1::PasswordsController#edit as HTML
  Parameters: {"reset_password_token"=>"[FILTERED]", "redirect_url"=>"http://127.0.0.1:3000"}
[31mUnpermitted parameter: :redirect_url[0m
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["reset_password_token", "c8de9019df5f5891c8b270d2ba062af9c3540578bcf44265d855cdfe108fb408"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "willard_gorczany@ohara.net"], ["id", 85], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "tokens" = $1, "allow_password_change" = $2, "updated_at" = $3 WHERE "users"."id" = $4[0m  [["tokens", "\"{\\\"PHRe6BgOnNZxkx8XJLCB9g\\\":{\\\"token\\\":\\\"$2a$10$UcyT9./Z4pUq7DTQuza00O9dTCD.n0m6dnnziQBg2a0aAi1noHR3O\\\",\\\"expiry\\\":1652828059,\\\"updated_at\\\":\\\"2020-05-17 22:54:18 UTC\\\"},\\\"K3___tZazKa5RA9axKX1yQ\\\":{\\\"token\\\":\\\"$2a$10$G7uNHLHb82A4RjlSXJzMX.1FXejvjqmHCDrdN87KDysU31TO46QIS\\\",\\\"expiry\\\":1652828059}}\""], ["allow_password_change", true], ["updated_at", "2020-05-17 22:54:19.104023"], ["id", 85]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Redirected to http://127.0.0.1:3000?access-token=Ybdt9-HCaltUMdrQpirCgQ&client=K3___tZazKa5RA9axKX1yQ&client_id=K3___tZazKa5RA9axKX1yQ&config=&expiry=1652828059&reset_password=true&token=Ybdt9-HCaltUMdrQpirCgQ&uid=willard_gorczany%40ohara.net
Completed 302 Found in 63ms (ActiveRecord: 1.4ms | Allocations: 1775)
Started PUT "/api/v1/users/password" for 127.0.0.1 at 2020-05-17 15:54:19 -0700
Processing by Api::V1::PasswordsController#update as JSON
  Parameters: {"password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "willard_gorczany@ohara.net"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.5ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "willard_gorczany@ohara.net"], ["id", 85], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK TO SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 85], ["LIMIT", 1]]
Completed 422 Unprocessable Entity in 65ms (Views: 0.2ms | ActiveRecord: 1.5ms | Allocations: 2884)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "reyes.hane@emard.info"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "a0197700-5360-4813-af87-6fe5e6d51261"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "reyes.hane@emard.info"], ["encrypted_password", "$2a$04$Oyw6UFWk/y9VQXcPHBCOZepw3HWJdOeVgSEFFU7tBiMTE7drJ7W9i"], ["username", "johnson_toy"], ["created_at", "2020-05-17 22:54:19.192914"], ["updated_at", "2020-05-17 22:54:19.192914"], ["uid", "reyes.hane@emard.info"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["reset_password_token", "7ef7b9ce49b35edee286a98c0e5c8603a439fddcdf6e61d4f99cfe3d32d8d7c5"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "reset_password_token" = $1, "reset_password_sent_at" = $2, "updated_at" = $3 WHERE "users"."id" = $4[0m  [["reset_password_token", "7ef7b9ce49b35edee286a98c0e5c8603a439fddcdf6e61d4f99cfe3d32d8d7c5"], ["reset_password_sent_at", "2020-05-17 22:54:19.195039"], ["updated_at", "2020-05-17 22:54:19.195209"], ["id", 86]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "reyes.hane@emard.info"], ["id", 86], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:19.256753"], ["tokens", "\"{\\\"XSlRJ0VJjqNtpu3FS_t2kA\\\":{\\\"token\\\":\\\"$2a$10$o8tmq7ZYx8v.A9FbgGrXxOga0lIOKCyNPMr3b8Obm4nX/Jt0BQQnu\\\",\\\"expiry\\\":1652828059,\\\"updated_at\\\":\\\"2020-05-17 22:54:19 UTC\\\"}}\""], ["id", 86]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started GET "/api/v1/users/password/edit?reset_password_token=[FILTERED]&redirect_url=http%3A%2F%2F127.0.0.1%3A3000" for 127.0.0.1 at 2020-05-17 15:54:19 -0700
Processing by Api::V1::PasswordsController#edit as HTML
  Parameters: {"reset_password_token"=>"[FILTERED]", "redirect_url"=>"http://127.0.0.1:3000"}
[31mUnpermitted parameter: :redirect_url[0m
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["reset_password_token", "7ef7b9ce49b35edee286a98c0e5c8603a439fddcdf6e61d4f99cfe3d32d8d7c5"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "reyes.hane@emard.info"], ["id", 86], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "tokens" = $1, "allow_password_change" = $2, "updated_at" = $3 WHERE "users"."id" = $4[0m  [["tokens", "\"{\\\"XSlRJ0VJjqNtpu3FS_t2kA\\\":{\\\"token\\\":\\\"$2a$10$o8tmq7ZYx8v.A9FbgGrXxOga0lIOKCyNPMr3b8Obm4nX/Jt0BQQnu\\\",\\\"expiry\\\":1652828059,\\\"updated_at\\\":\\\"2020-05-17 22:54:19 UTC\\\"},\\\"NI3gEtX4VrO2CIRKTxSc7w\\\":{\\\"token\\\":\\\"$2a$10$b0wyMiXBlunARKr32flLzubSr9vL5MlzMHuVNVoDW8Au/mQPE1hnG\\\",\\\"expiry\\\":1652828059}}\""], ["allow_password_change", true], ["updated_at", "2020-05-17 22:54:19.333984"], ["id", 86]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Redirected to http://127.0.0.1:3000?access-token=apgtAWzZKJhDLGGyVMf38A&client=NI3gEtX4VrO2CIRKTxSc7w&client_id=NI3gEtX4VrO2CIRKTxSc7w&config=&expiry=1652828059&reset_password=true&token=apgtAWzZKJhDLGGyVMf38A&uid=reyes.hane%40emard.info
Completed 302 Found in 62ms (ActiveRecord: 1.7ms | Allocations: 1624)
Started PUT "/api/v1/users/password" for 127.0.0.1 at 2020-05-17 15:54:19 -0700
Processing by Api::V1::PasswordsController#update as JSON
  Parameters: {"password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "reyes.hane@emard.info"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "reyes.hane@emard.info"], ["id", 86], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "encrypted_password" = $1, "reset_password_token" = $2, "reset_password_sent_at" = $3, "updated_at" = $4 WHERE "users"."id" = $5[0m  [["encrypted_password", "$2a$04$bXJUIj1jxOwW0AqXFJ9D4erTgSSb6NALUHc3rxcVCBxCPCTIYuTPi"], ["reset_password_token", nil], ["reset_password_sent_at", nil], ["updated_at", "2020-05-17 22:54:19.412195"], ["id", 86]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "reyes.hane@emard.info"], ["id", 86], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "allow_password_change" = $1, "updated_at" = $2 WHERE "users"."id" = $3[0m  [["allow_password_change", false], ["updated_at", "2020-05-17 22:54:19.415571"], ["id", 86]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 86], ["LIMIT", 1]]
Completed 200 OK in 67ms (Views: 0.2ms | ActiveRecord: 3.0ms | Allocations: 3195)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.4ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "everette_terry@lang.name"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "c76c1358-d346-42fb-b9cd-4e66f5fdc0db"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "everette_terry@lang.name"], ["encrypted_password", "$2a$04$J6YcG6cRKad5LPjW2tBHw.qowpUKC3oaszD29M2keT2DvhWhw6Syu"], ["username", "paris"], ["created_at", "2020-05-17 22:54:19.426362"], ["updated_at", "2020-05-17 22:54:19.426362"], ["uid", "everette_terry@lang.name"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "everette_terry@lang.name"], ["id", 87], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:19.485958"], ["tokens", "\"{\\\"jtgEr7BOrtVp0hlI7q44vw\\\":{\\\"token\\\":\\\"$2a$10$FOiU.4OlfHHz1aJEZ.5Zg.90YLNnQcJm5yiIodA2in0qXpn54Rdk6\\\",\\\"expiry\\\":1652828059,\\\"updated_at\\\":\\\"2020-05-17 22:54:19 UTC\\\"}}\""], ["id", 87]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started PUT "/api/v1/user" for 127.0.0.1 at 2020-05-17 15:54:19 -0700
Processing by Api::V1::UsersController#update as JSON
  Parameters: {"user"=>{}}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "everette_terry@lang.name"], ["LIMIT", 1]]
param is missing or the value is empty: user
Completed 422 Unprocessable Entity in 58ms (Views: 0.2ms | ActiveRecord: 0.3ms | Allocations: 603)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "don@davis.io"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "fef2ba0f-05ca-445c-802b-3121c35e3e25"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "don@davis.io"], ["encrypted_password", "$2a$04$RhtEIcxwCQtr01IrH6rZr.Hrte9yQSGarU4tDIRIdBoTyuA7sdmG6"], ["username", "jarrod_lubowitz"], ["created_at", "2020-05-17 22:54:19.566223"], ["updated_at", "2020-05-17 22:54:19.566223"], ["uid", "don@davis.io"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "don@davis.io"], ["id", 88], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:19.626105"], ["tokens", "\"{\\\"mLQTB4DPisROJe4t0R6eqw\\\":{\\\"token\\\":\\\"$2a$10$nMq4zdfJoNx85IVp80kd6ODNmo/gYex3AoLf1qaPGUQi71Oo/t0Ri\\\",\\\"expiry\\\":1652828059,\\\"updated_at\\\":\\\"2020-05-17 22:54:19 UTC\\\"}}\""], ["id", 88]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started PUT "/api/v1/user" for 127.0.0.1 at 2020-05-17 15:54:19 -0700
Processing by Api::V1::UsersController#update as JSON
  Parameters: {"user"=>{"email"=>"notanemail"}}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "don@davis.io"], ["LIMIT", 1]]
  [1m[35m (0.4ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "don@davis.io"], ["id", 88], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK TO SAVEPOINT active_record_1[0m
Validation failed: Email is not an email
Completed 400 Bad Request in 61ms (Views: 0.2ms | ActiveRecord: 1.3ms | Allocations: 1432)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "keneth@homenick.net"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "99456787-e3cb-45fc-a628-2e7d2534cea8"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "keneth@homenick.net"], ["encrypted_password", "$2a$04$ukyHDeYZ0rQsMSHVTBm0bOghNWe4aMOeFcH764TUVDDmIoz66rAAO"], ["username", "trula"], ["created_at", "2020-05-17 22:54:19.709916"], ["updated_at", "2020-05-17 22:54:19.709916"], ["uid", "keneth@homenick.net"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "keneth@homenick.net"], ["id", 89], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:19.770157"], ["tokens", "\"{\\\"LSq8qxMb6HEh-S2qTcdTrg\\\":{\\\"token\\\":\\\"$2a$10$6y/cxE9NHGsvdDPnyL5WseuMpKIueNz8RakQAAtsQBl1jP9ESRtfe\\\",\\\"expiry\\\":1652828059,\\\"updated_at\\\":\\\"2020-05-17 22:54:19 UTC\\\"}}\""], ["id", 89]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started PUT "/api/v1/user" for 127.0.0.1 at 2020-05-17 15:54:19 -0700
Processing by Api::V1::UsersController#update as JSON
  Parameters: {"user"=>{"email"=>"notanemail"}}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "keneth@homenick.net"], ["LIMIT", 1]]
  [1m[35m (0.4ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "keneth@homenick.net"], ["id", 89], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK TO SAVEPOINT active_record_1[0m
Validation failed: Email is not an email
Completed 400 Bad Request in 61ms (Views: 0.2ms | ActiveRecord: 1.4ms | Allocations: 1412)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "lane@adamsbauch.net"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "c6c8364f-4034-46f7-b9fd-c994be475497"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "lane@adamsbauch.net"], ["encrypted_password", "$2a$04$N3XupE8YsLm1bocpGKvVkuDJSRRX8pO2PZ3ssLjBD6p.Jo1mwFDVy"], ["username", "gale"], ["created_at", "2020-05-17 22:54:19.855206"], ["updated_at", "2020-05-17 22:54:19.855206"], ["uid", "lane@adamsbauch.net"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "lane@adamsbauch.net"], ["id", 90], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:19.915270"], ["tokens", "\"{\\\"0gxlke8wDTFGRaG028nuRg\\\":{\\\"token\\\":\\\"$2a$10$sTWptFRsx9imGkzf1AhhJeux2sKsSfeCh0kNNacKA7c.vhx7WN4WG\\\",\\\"expiry\\\":1652828059,\\\"updated_at\\\":\\\"2020-05-17 22:54:19 UTC\\\"}}\""], ["id", 90]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started PUT "/api/v1/user" for 127.0.0.1 at 2020-05-17 15:54:19 -0700
Processing by Api::V1::UsersController#update as JSON
  Parameters: {"user"=>{"email"=>"notanemail"}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "lane@adamsbauch.net"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "lane@adamsbauch.net"], ["id", 90], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK TO SAVEPOINT active_record_1[0m
Validation failed: Email is not an email
Completed 400 Bad Request in 60ms (Views: 0.2ms | ActiveRecord: 1.3ms | Allocations: 1412)
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 90], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "bud@bechtelar.net"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "e25da8bf-3222-446a-b055-015e3f8dc80d"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "bud@bechtelar.net"], ["encrypted_password", "$2a$04$EYb.6NwAaNQBvBb7/4lzVO2Go2qvsbDPq29ZnAsVjtfLNJzdbVd.K"], ["username", "zachariah_streich"], ["created_at", "2020-05-17 22:54:19.999356"], ["updated_at", "2020-05-17 22:54:19.999356"], ["uid", "bud@bechtelar.net"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "bud@bechtelar.net"], ["id", 91], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:20.060255"], ["tokens", "\"{\\\"s4Zgw_wSfBb57JNWTwMsqQ\\\":{\\\"token\\\":\\\"$2a$10$aFbg1BLxf1cqSsoGTctkl.vIhWPTTY4AH6.N9uo9HJ.QuelbxRNmm\\\",\\\"expiry\\\":1652828060,\\\"updated_at\\\":\\\"2020-05-17 22:54:20 UTC\\\"}}\""], ["id", 91]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started PUT "/api/v1/user" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::UsersController#update as JSON
  Parameters: {"user"=>{"username"=>"new username"}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "bud@bechtelar.net"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "bud@bechtelar.net"], ["id", 91], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "username" = $1, "updated_at" = $2 WHERE "users"."id" = $3[0m  [["username", "new username"], ["updated_at", "2020-05-17 22:54:20.136365"], ["id", 91]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  Rendering api/v1/users/show.json.jbuilder
  Rendered api/v1/users/_info.json.jbuilder (Duration: 0.1ms | Allocations: 31)
  Rendered api/v1/users/show.json.jbuilder (Duration: 0.3ms | Allocations: 207)
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 91], ["LIMIT", 1]]
Completed 200 OK in 63ms (Views: 0.6ms | ActiveRecord: 1.6ms | Allocations: 2052)
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "carmelo_hoeger@stoltenbergjohns.net"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "2c586d09-66e7-4549-84fa-28ce422387d0"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "carmelo_hoeger@stoltenbergjohns.net"], ["encrypted_password", "$2a$04$jYpQIB37NVepL0PIJcG4/eqmXammPfR0keJZQtOGgHx3NqoFCIFkW"], ["username", "antony"], ["created_at", "2020-05-17 22:54:20.145190"], ["updated_at", "2020-05-17 22:54:20.145190"], ["uid", "carmelo_hoeger@stoltenbergjohns.net"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "carmelo_hoeger@stoltenbergjohns.net"], ["id", 92], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:20.204593"], ["tokens", "\"{\\\"PSZrs52OKf0HLrCGuSsa8Q\\\":{\\\"token\\\":\\\"$2a$10$HiBI1rHae9DgYIzNwDjfP.nup99AyZRP1hiQaliszDuO7qP4KPoNu\\\",\\\"expiry\\\":1652828060,\\\"updated_at\\\":\\\"2020-05-17 22:54:20 UTC\\\"}}\""], ["id", 92]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started PUT "/api/v1/user" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::UsersController#update as JSON
  Parameters: {"user"=>{"username"=>"new username"}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "carmelo_hoeger@stoltenbergjohns.net"], ["LIMIT", 1]]
  [1m[35m (0.4ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.5ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "carmelo_hoeger@stoltenbergjohns.net"], ["id", 92], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "username" = $1, "updated_at" = $2 WHERE "users"."id" = $3[0m  [["username", "new username"], ["updated_at", "2020-05-17 22:54:20.280984"], ["id", 92]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  Rendering api/v1/users/show.json.jbuilder
  Rendered api/v1/users/_info.json.jbuilder (Duration: 0.1ms | Allocations: 31)
  Rendered api/v1/users/show.json.jbuilder (Duration: 0.3ms | Allocations: 208)
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 92], ["LIMIT", 1]]
Completed 200 OK in 63ms (Views: 0.7ms | ActiveRecord: 2.1ms | Allocations: 2056)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "merrie@feil.net"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "4edee141-0ab5-4c8e-9be7-abfff289d702"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "merrie@feil.net"], ["encrypted_password", "$2a$04$iJgiPj6Ow/O6U6Upkm/DDeY5l8lPjxRkt6Z82AzZjArIxaq/IqASi"], ["username", "malika"], ["created_at", "2020-05-17 22:54:20.290985"], ["updated_at", "2020-05-17 22:54:20.290985"], ["uid", "merrie@feil.net"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.5ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.5ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "merrie@feil.net"], ["id", 93], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:20.350768"], ["tokens", "\"{\\\"rdxdl3ZmdxPbYX46HTBobw\\\":{\\\"token\\\":\\\"$2a$10$01HIbp12VlNcVxZpVgFKfu2shzvx..N8Ai6eQ984K3L36vXyVz8JC\\\",\\\"expiry\\\":1652828060,\\\"updated_at\\\":\\\"2020-05-17 22:54:20 UTC\\\"}}\""], ["id", 93]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started PUT "/api/v1/user" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::UsersController#update as JSON
  Parameters: {"user"=>{"username"=>"new username"}}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "merrie@feil.net"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "merrie@feil.net"], ["id", 93], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "username" = $1, "updated_at" = $2 WHERE "users"."id" = $3[0m  [["username", "new username"], ["updated_at", "2020-05-17 22:54:20.426237"], ["id", 93]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  Rendering api/v1/users/show.json.jbuilder
  Rendered api/v1/users/_info.json.jbuilder (Duration: 0.1ms | Allocations: 31)
  Rendered api/v1/users/show.json.jbuilder (Duration: 0.3ms | Allocations: 207)
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 93], ["LIMIT", 1]]
Completed 200 OK in 63ms (Views: 0.6ms | ActiveRecord: 1.8ms | Allocations: 2052)
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 93], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
Started POST "/api/v1/users" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::RegistrationsController#create as JSON
  Parameters: {"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}, "registration"=>{"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}}}
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "first_name", "last_name", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"[0m  [["email", "test@test.com"], ["encrypted_password", "$2a$04$AdqPLvspS8GQm4a5o9TEUOhooz21nu23GJat2BYVpsd0JYDH3do2W"], ["first_name", "Johnny"], ["last_name", "Perez"], ["username", "test"], ["created_at", "2020-05-17 22:54:20.455906"], ["updated_at", "2020-05-17 22:54:20.455906"], ["uid", "test@test.com"]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "test@test.com"], ["id", 94], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:20.514868"], ["tokens", "\"{\\\"Nq4YtwEQKc2wtCRAbW6RZA\\\":{\\\"token\\\":\\\"$2a$10$Bz7CPcLm..MF1iG..Rhcwu61S7Nt5YfPrxVGTzu3j7miPe/M.JPlW\\\",\\\"expiry\\\":1652828060}}\""], ["id", 94]]
  [1m[35m (0.3ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 94], ["LIMIT", 1]]
Completed 200 OK in 67ms (Views: 0.2ms | ActiveRecord: 2.8ms | Allocations: 3248)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT COUNT(*) FROM "users"[0m
Started POST "/api/v1/users" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::RegistrationsController#create as JSON
  Parameters: {"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}, "registration"=>{"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}}}
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.4ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "first_name", "last_name", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"[0m  [["email", "test@test.com"], ["encrypted_password", "$2a$04$pBI1FQ.ZvuJJSvaDYmXmCOFGkITbDcWWzID.x7YKHGCMAmCzrRozu"], ["first_name", "Johnny"], ["last_name", "Perez"], ["username", "test"], ["created_at", "2020-05-17 22:54:20.540734"], ["updated_at", "2020-05-17 22:54:20.540734"], ["uid", "test@test.com"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "test@test.com"], ["id", 95], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:20.599624"], ["tokens", "\"{\\\"SYwe_IMtMJlDdfw4YI5JAg\\\":{\\\"token\\\":\\\"$2a$10$uP5G93jWPmnyk5o8Hje75.pJX1rvj4CoRikBPmfYrK40FvTcdg2d2\\\",\\\"expiry\\\":1652828060}}\""], ["id", 95]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 95], ["LIMIT", 1]]
Completed 200 OK in 66ms (Views: 0.2ms | ActiveRecord: 2.4ms | Allocations: 3042)
  [1m[35m (0.2ms)[0m  [1m[34mSELECT COUNT(*) FROM "users"[0m
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
Started POST "/api/v1/users" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::RegistrationsController#create as JSON
  Parameters: {"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}, "registration"=>{"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}}}
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "first_name", "last_name", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"[0m  [["email", "test@test.com"], ["encrypted_password", "$2a$04$Sy5VN/VpjZT353gHLefgCOnb8TtpEbyRHo05Uwm3UEhZu3EQ/Et6i"], ["first_name", "Johnny"], ["last_name", "Perez"], ["username", "test"], ["created_at", "2020-05-17 22:54:20.624051"], ["updated_at", "2020-05-17 22:54:20.624051"], ["uid", "test@test.com"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.5ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "test@test.com"], ["id", 96], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:20.683850"], ["tokens", "\"{\\\"5_F3JsqLZW1zxF7ggxx6ng\\\":{\\\"token\\\":\\\"$2a$10$.ywuaOyMyJMk3MCTJifL8uEP3/vodu5.zpNtKNPbEw6raSjigyUcG\\\",\\\"expiry\\\":1652828060}}\""], ["id", 96]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 96], ["LIMIT", 1]]
Completed 200 OK in 67ms (Views: 0.2ms | ActiveRecord: 2.7ms | Allocations: 3042)
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1[0m  [["LIMIT", 1]]
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
Started POST "/api/v1/users" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::RegistrationsController#create as JSON
  Parameters: {"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}, "registration"=>{"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}}}
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK TO SAVEPOINT active_record_1[0m
Completed 422 Unprocessable Entity in 6ms (Views: 0.3ms | ActiveRecord: 0.9ms | Allocations: 2181)
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
Started POST "/api/v1/users" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::RegistrationsController#create as JSON
  Parameters: {"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}, "registration"=>{"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}}}
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK TO SAVEPOINT active_record_1[0m
Completed 422 Unprocessable Entity in 6ms (Views: 0.3ms | ActiveRecord: 1.1ms | Allocations: 2180)
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2[0m  [["email", "test@test.com"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[34mSELECT COUNT(*) FROM "users"[0m
Started POST "/api/v1/users" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::RegistrationsController#create as JSON
  Parameters: {"user"=>{"username"=>"test", "email"=>"invalid_email", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}, "registration"=>{"user"=>{"username"=>"test", "email"=>"invalid_email", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}}}
  [1m[35m (0.4ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "invalid_email"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "invalid_email"], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK TO SAVEPOINT active_record_1[0m
Completed 422 Unprocessable Entity in 6ms (Views: 0.2ms | ActiveRecord: 1.2ms | Allocations: 1789)
  [1m[35m (0.2ms)[0m  [1m[34mSELECT COUNT(*) FROM "users"[0m
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
Started POST "/api/v1/users" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::RegistrationsController#create as JSON
  Parameters: {"user"=>{"username"=>"test", "email"=>"invalid_email", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}, "registration"=>{"user"=>{"username"=>"test", "email"=>"invalid_email", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}}}
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "invalid_email"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "invalid_email"], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK TO SAVEPOINT active_record_1[0m
Completed 422 Unprocessable Entity in 6ms (Views: 0.2ms | ActiveRecord: 1.2ms | Allocations: 1779)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
Started POST "/api/v1/users" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::RegistrationsController#create as JSON
  Parameters: {"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}, "registration"=>{"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}}}
  [1m[35m (0.4ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK TO SAVEPOINT active_record_1[0m
Completed 422 Unprocessable Entity in 6ms (Views: 0.2ms | ActiveRecord: 1.1ms | Allocations: 2132)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
Started POST "/api/v1/users" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::RegistrationsController#create as JSON
  Parameters: {"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}, "registration"=>{"user"=>{"username"=>"test", "email"=>"test@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Johnny", "last_name"=>"Perez"}}}
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "test@test.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK TO SAVEPOINT active_record_1[0m
Completed 422 Unprocessable Entity in 6ms (Views: 0.2ms | ActiveRecord: 0.9ms | Allocations: 2073)
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2[0m  [["email", "test@test.com"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
Started GET "/api/v1/status" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::ApiController#status as JSON
  Parameters: {"api"=>{}}
Completed 500 Internal Server Error in 1ms (Views: 0.1ms | ActiveRecord: 0.0ms | Allocations: 385)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
Started GET "/api/v1/status" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::ApiController#status as JSON
  Parameters: {"api"=>{}}
Completed 500 Internal Server Error in 1ms (Views: 0.1ms | ActiveRecord: 0.0ms | Allocations: 271)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
Started GET "/api/v1/status" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::ApiController#status as JSON
Filter chain halted as :check_json_request rendered or redirected
Completed 406 Not Acceptable in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms | Allocations: 142)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mSetting Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "settings" WHERE "settings"."key" = $1 LIMIT $2[0m  [["key", "min_version"], ["LIMIT", 1]]
  [1m[36mSetting Create (0.3ms)[0m  [1m[32mINSERT INTO "settings" ("key", "value") VALUES ($1, $2) RETURNING "id"[0m  [["key", "min_version"], ["value", "0.0"]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started GET "/api/v1/settings/must_update" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::SettingsController#must_update as JSON
  Parameters: {"device_version"=>"1.0", "api"=>{"device_version"=>"1.0"}}
  [1m[36mSetting Load (0.5ms)[0m  [1m[34mSELECT "settings".* FROM "settings" WHERE "settings"."key" = $1 LIMIT $2[0m  [["key", "min_version"], ["LIMIT", 1]]
  [1m[36mCACHE Setting Load (0.0ms)[0m  [1m[34mSELECT "settings".* FROM "settings" WHERE "settings"."key" = $1 LIMIT $2[0m  [["key", "min_version"], ["LIMIT", 1]]
Completed 200 OK in 3ms (Views: 0.2ms | ActiveRecord: 0.5ms | Allocations: 626)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mSetting Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "settings" WHERE "settings"."key" = $1 LIMIT $2[0m  [["key", "min_version"], ["LIMIT", 1]]
  [1m[36mSetting Create (0.3ms)[0m  [1m[32mINSERT INTO "settings" ("key", "value") VALUES ($1, $2) RETURNING "id"[0m  [["key", "min_version"], ["value", "0.0"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started GET "/api/v1/settings/must_update" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::SettingsController#must_update as JSON
  Parameters: {"device_version"=>"1.0", "api"=>{"device_version"=>"1.0"}}
  [1m[36mSetting Load (0.4ms)[0m  [1m[34mSELECT "settings".* FROM "settings" WHERE "settings"."key" = $1 LIMIT $2[0m  [["key", "min_version"], ["LIMIT", 1]]
  [1m[36mCACHE Setting Load (0.0ms)[0m  [1m[34mSELECT "settings".* FROM "settings" WHERE "settings"."key" = $1 LIMIT $2[0m  [["key", "min_version"], ["LIMIT", 1]]
Completed 200 OK in 2ms (Views: 0.1ms | ActiveRecord: 0.4ms | Allocations: 427)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.1ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mSetting Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "settings" WHERE "settings"."key" = $1 LIMIT $2[0m  [["key", "min_version"], ["LIMIT", 1]]
  [1m[36mSetting Create (0.2ms)[0m  [1m[32mINSERT INTO "settings" ("key", "value") VALUES ($1, $2) RETURNING "id"[0m  [["key", "min_version"], ["value", "2.0"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started GET "/api/v1/settings/must_update" for 127.0.0.1 at 2020-05-17 15:54:20 -0700
Processing by Api::V1::SettingsController#must_update as JSON
  Parameters: {"device_version"=>"1.0", "api"=>{"device_version"=>"1.0"}}
  [1m[36mSetting Load (0.3ms)[0m  [1m[34mSELECT "settings".* FROM "settings" WHERE "settings"."key" = $1 LIMIT $2[0m  [["key", "min_version"], ["LIMIT", 1]]
  [1m[36mCACHE Setting Load (0.0ms)[0m  [1m[34mSELECT "settings".* FROM "settings" WHERE "settings"."key" = $1 LIMIT $2[0m  [["key", "min_version"], ["LIMIT", 1]]
Completed 200 OK in 2ms (Views: 0.1ms | ActiveRecord: 0.3ms | Allocations: 427)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
Started GET "/api/v1/settings/must_update" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::SettingsController#must_update as JSON
  Parameters: {"device_version"=>"1.0", "api"=>{"device_version"=>"1.0"}}
  [1m[36mSetting Load (0.4ms)[0m  [1m[34mSELECT "settings".* FROM "settings" WHERE "settings"."key" = $1 LIMIT $2[0m  [["key", "min_version"], ["LIMIT", 1]]
Completed 200 OK in 1ms (Views: 0.1ms | ActiveRecord: 0.4ms | Allocations: 278)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "bree.cartwright@feeney.io"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "a51b793f-e11f-4e5a-b47f-b14141dc1b7e"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "bree.cartwright@feeney.io"], ["encrypted_password", "$2a$04$oXHKsvvTdv6GVhAYETYmVePUtcAn/oZUSZUgmuwYaKmhPtfJQgXZW"], ["username", "kary_ullrich"], ["created_at", "2020-05-17 22:54:21.021659"], ["updated_at", "2020-05-17 22:54:21.021659"], ["uid", "bree.cartwright@feeney.io"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.5ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "bree.cartwright@feeney.io"], ["id", 97], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:21.080620"], ["tokens", "\"{\\\"IN-r_Kjopv_dsOXx5lT9nA\\\":{\\\"token\\\":\\\"$2a$10$nA8mo8R3nVXWzwpiLe2ZGubmB1hnXvP6GZXsFcSdvtAowIL3Rfws.\\\",\\\"expiry\\\":1652828061,\\\"updated_at\\\":\\\"2020-05-17 22:54:21 UTC\\\"}}\""], ["id", 97]]
  [1m[35m (0.3ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started GET "/api/v1/user" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::UsersController#show as JSON
  Parameters: {"user"=>{}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "bree.cartwright@feeney.io"], ["LIMIT", 1]]
  Rendering api/v1/users/show.json.jbuilder
  Rendered api/v1/users/_info.json.jbuilder (Duration: 0.1ms | Allocations: 35)
  Rendered api/v1/users/show.json.jbuilder (Duration: 0.3ms | Allocations: 212)
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 97], ["LIMIT", 1]]
Completed 200 OK in 59ms (Views: 0.7ms | ActiveRecord: 0.7ms | Allocations: 1207)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.4ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "jamal@fadel.co"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "79a330a2-4b8b-4d3c-9f58-1f516408ad8e"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "jamal@fadel.co"], ["encrypted_password", "$2a$04$u645HDS/qPSrzcQUeDy.IuLv5YMoNrTkw28.2cL3BKpVVtt0qR3fW"], ["username", "wally_trantow"], ["created_at", "2020-05-17 22:54:21.163841"], ["updated_at", "2020-05-17 22:54:21.163841"], ["uid", "jamal@fadel.co"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.4ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "jamal@fadel.co"], ["id", 98], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "updated_at" = $1, "tokens" = $2 WHERE "users"."id" = $3[0m  [["updated_at", "2020-05-17 22:54:21.223052"], ["tokens", "\"{\\\"UobNscq_VLkzjUHpOcXupA\\\":{\\\"token\\\":\\\"$2a$10$r.5JlEwlslsVS56JM4/65OInwaPknWfrBLzqNYM9YRgyto8YZJzdi\\\",\\\"expiry\\\":1652828061,\\\"updated_at\\\":\\\"2020-05-17 22:54:21 UTC\\\"}}\""], ["id", 98]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started GET "/api/v1/user" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::UsersController#show as JSON
  Parameters: {"user"=>{}}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2[0m  [["uid", "jamal@fadel.co"], ["LIMIT", 1]]
  Rendering api/v1/users/show.json.jbuilder
  Rendered api/v1/users/_info.json.jbuilder (Duration: 0.1ms | Allocations: 34)
  Rendered api/v1/users/show.json.jbuilder (Duration: 0.3ms | Allocations: 210)
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 98], ["LIMIT", 1]]
Completed 200 OK in 60ms (Views: 0.7ms | ActiveRecord: 0.6ms | Allocations: 1195)
  [1m[35m (0.4ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "ann_altenwerth@williamson.co"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "70ed93fa-b142-445b-b85d-98b4d9cb31f7"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "ann_altenwerth@williamson.co"], ["encrypted_password", "$2a$04$dYGZfYrruIipLy2JzWISS.5dCakJcY0i5K2dmgf7rDIQtyYl0P9pa"], ["username", "carri_vandervort"], ["created_at", "2020-05-17 22:54:21.306220"], ["updated_at", "2020-05-17 22:54:21.306220"], ["uid", "ann_altenwerth@williamson.co"]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started POST "/api/v1/users/sign_in" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::SessionsController#create as JSON
  Parameters: {"user"=>{"email"=>"ann_altenwerth@williamson.co", "password"=>"[FILTERED]"}, "session"=>{"user"=>{"email"=>"ann_altenwerth@williamson.co", "password"=>"[FILTERED]"}}}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "ann_altenwerth@williamson.co"], ["provider", "email"], ["LIMIT", 1]]
Completed 401 Unauthorized in 4ms (Views: 0.2ms | ActiveRecord: 0.3ms | Allocations: 723)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "stefan.paucek@veum.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "3b1a6650-8dcb-4632-8f9e-c7e82825b003"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "stefan.paucek@veum.com"], ["encrypted_password", "$2a$04$nzac9M.3fvhqoPavvH0J9eszKtFjBkvkSCLV4VQEYsUx991kHF0na"], ["username", "agatha.torp"], ["created_at", "2020-05-17 22:54:21.331818"], ["updated_at", "2020-05-17 22:54:21.331818"], ["uid", "stefan.paucek@veum.com"]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started POST "/api/v1/users/sign_in" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::SessionsController#create as JSON
  Parameters: {"user"=>{"email"=>"stefan.paucek@veum.com", "password"=>"[FILTERED]"}, "session"=>{"user"=>{"email"=>"stefan.paucek@veum.com", "password"=>"[FILTERED]"}}}
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "stefan.paucek@veum.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.5ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "stefan.paucek@veum.com"], ["id", 100], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "tokens" = $1, "updated_at" = $2 WHERE "users"."id" = $3[0m  [["tokens", "\"{\\\"poDFJNz3USF2uguuRPXQ8w\\\":{\\\"token\\\":\\\"$2a$10$nwonwDTXndGuD4hoQyfbPeWCtqoR04hqFotKd61ArOgEbmLQ8x6Tu\\\",\\\"expiry\\\":1652828061}}\""], ["updated_at", "2020-05-17 22:54:21.409608"], ["id", 100]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "sign_in_count" = $1, "current_sign_in_at" = $2, "last_sign_in_at" = $3, "current_sign_in_ip" = $4, "last_sign_in_ip" = $5, "updated_at" = $6 WHERE "users"."id" = $7[0m  [["sign_in_count", 1], ["current_sign_in_at", "2020-05-17 22:54:21.411100"], ["last_sign_in_at", "2020-05-17 22:54:21.411100"], ["current_sign_in_ip", "127.0.0.1/32"], ["last_sign_in_ip", "127.0.0.1/32"], ["updated_at", "2020-05-17 22:54:21.411349"], ["id", 100]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 100], ["LIMIT", 1]]
Completed 200 OK in 66ms (Views: 0.2ms | ActiveRecord: 2.6ms | Allocations: 2834)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "alphonso@schneider.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "6780242a-d348-4b2b-8e8e-c563d65bc37f"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "alphonso@schneider.com"], ["encrypted_password", "$2a$04$6XpTeSWnjMpCiCaDNJecreajlf6Aq5IEJ8RP3okLKGxkyqoUeHgBa"], ["username", "raymond.boyle"], ["created_at", "2020-05-17 22:54:21.420319"], ["updated_at", "2020-05-17 22:54:21.420319"], ["uid", "alphonso@schneider.com"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started POST "/api/v1/users/sign_in" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::SessionsController#create as JSON
  Parameters: {"user"=>{"email"=>"alphonso@schneider.com", "password"=>"[FILTERED]"}, "session"=>{"user"=>{"email"=>"alphonso@schneider.com", "password"=>"[FILTERED]"}}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "alphonso@schneider.com"], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "alphonso@schneider.com"], ["id", 101], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "tokens" = $1, "updated_at" = $2 WHERE "users"."id" = $3[0m  [["tokens", "\"{\\\"EhnTuqeCq3t_G-zD7WynOQ\\\":{\\\"token\\\":\\\"$2a$10$jj6O9RQRn.t4PEjnDNdYseto3/OUq9XWwOYOs3k9sfwBB9mRvee6q\\\",\\\"expiry\\\":1652828061}}\""], ["updated_at", "2020-05-17 22:54:21.496953"], ["id", 101]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Update (0.5ms)[0m  [1m[33mUPDATE "users" SET "sign_in_count" = $1, "current_sign_in_at" = $2, "last_sign_in_at" = $3, "current_sign_in_ip" = $4, "last_sign_in_ip" = $5, "updated_at" = $6 WHERE "users"."id" = $7[0m  [["sign_in_count", 1], ["current_sign_in_at", "2020-05-17 22:54:21.498508"], ["last_sign_in_at", "2020-05-17 22:54:21.498508"], ["current_sign_in_ip", "127.0.0.1/32"], ["last_sign_in_ip", "127.0.0.1/32"], ["updated_at", "2020-05-17 22:54:21.498820"], ["id", 101]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 101], ["LIMIT", 1]]
Completed 200 OK in 66ms (Views: 0.2ms | ActiveRecord: 2.8ms | Allocations: 2779)
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 101], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "ervin@nitzsche.org"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "c2bc7543-d390-4dd1-afbb-9bcfe663ae6f"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "ervin@nitzsche.org"], ["encrypted_password", "$2a$04$S3w4n82E.9O324urhh1PrO5eaAbd1nvHyeCr01wjosuoD0niGjAoK"], ["username", "dexter"], ["created_at", "2020-05-17 22:54:21.564464"], ["updated_at", "2020-05-17 22:54:21.564464"], ["uid", "ervin@nitzsche.org"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started POST "/api/v1/users/sign_in" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::SessionsController#create as JSON
  Parameters: {"user"=>{"email"=>"ervin@nitzsche.org", "password"=>"[FILTERED]"}, "session"=>{"user"=>{"email"=>"ervin@nitzsche.org", "password"=>"[FILTERED]"}}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "ervin@nitzsche.org"], ["provider", "email"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "ervin@nitzsche.org"], ["id", 102], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "tokens" = $1, "updated_at" = $2 WHERE "users"."id" = $3[0m  [["tokens", "\"{\\\"2BKlE9xbRd6vvBWS6K7XXA\\\":{\\\"token\\\":\\\"$2a$10$ixaW0eu07RkPAcH7dcheS.vAE3zydrm1RfWVYTufM4oKNpeS86Cr2\\\",\\\"expiry\\\":1652828061}}\""], ["updated_at", "2020-05-17 22:54:21.641214"], ["id", 102]]
  [1m[35m (0.4ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Update (0.4ms)[0m  [1m[33mUPDATE "users" SET "sign_in_count" = $1, "current_sign_in_at" = $2, "last_sign_in_at" = $3, "current_sign_in_ip" = $4, "last_sign_in_ip" = $5, "updated_at" = $6 WHERE "users"."id" = $7[0m  [["sign_in_count", 1], ["current_sign_in_at", "2020-05-17 22:54:21.643166"], ["last_sign_in_at", "2020-05-17 22:54:21.643166"], ["current_sign_in_ip", "127.0.0.1/32"], ["last_sign_in_ip", "127.0.0.1/32"], ["updated_at", "2020-05-17 22:54:21.643565"], ["id", 102]]
  [1m[35m (0.4ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 102], ["LIMIT", 1]]
Completed 200 OK in 67ms (Views: 0.2ms | ActiveRecord: 3.0ms | Allocations: 2779)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "wonda.ohara@ratkepadberg.name"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "d61cb0d5-429a-4277-8312-e360070fcd22"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "wonda.ohara@ratkepadberg.name"], ["encrypted_password", "$2a$04$sGn8jFHv.loAupbSqHna8uAWxQtsJtZbu9CPSjNnDWqW/rdB/YJUK"], ["username", "trey_cruickshank"], ["created_at", "2020-05-17 22:54:21.654020"], ["updated_at", "2020-05-17 22:54:21.654020"], ["uid", "wonda.ohara@ratkepadberg.name"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "marianela@boyerheidenreich.co"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "7063ed67-037e-4689-be34-9b0b52979002"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "marianela@boyerheidenreich.co"], ["encrypted_password", "$2a$04$YPqeJ8klv3zh4i1lI8prgOrB4kvuZvdc/QYu6VCNuO0zbChL5Ti26"], ["username", "whitney"], ["created_at", "2020-05-17 22:54:21.658846"], ["updated_at", "2020-05-17 22:54:21.658846"], ["uid", "marianela@boyerheidenreich.co"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "siobhan_ortiz@nitzsche.net"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "8b5ac6cc-937a-4ecc-be60-d2019a40d60e"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "siobhan_ortiz@nitzsche.net"], ["encrypted_password", "$2a$04$nBefNQ5Xgof5FwNAwoxWfu0ATk1t6WJDsELCVioLZxyMdspe092Qy"], ["username", "margareta_farrell"], ["created_at", "2020-05-17 22:54:21.665332"], ["updated_at", "2020-05-17 22:54:21.665332"], ["uid", "siobhan_ortiz@nitzsche.net"]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.1ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "maida_collier@leuschke.biz"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "42b72de3-3191-4e2c-b834-9b5c7ac239b7"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "maida_collier@leuschke.biz"], ["encrypted_password", "$2a$04$bythLvUCrKqQ.yF5kYP5/OqQVA3XEsTA11SUKhO2VYcKv04R6TXRy"], ["username", "jen"], ["created_at", "2020-05-17 22:54:21.671999"], ["updated_at", "2020-05-17 22:54:21.671999"], ["uid", "maida_collier@leuschke.biz"]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started POST "/api/v1/users/password" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::PasswordsController#create as JSON
  Parameters: {"email"=>"notvalid@example.com", "password"=>{"email"=>"notvalid@example.com"}}
[31mUnpermitted parameter: :password[0m
[31mUnpermitted parameter: :password[0m
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "notvalid@example.com"], ["provider", "email"], ["LIMIT", 1]]
Completed 404 Not Found in 2ms (Views: 0.1ms | ActiveRecord: 0.3ms | Allocations: 573)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "soila_stracke@roberts.co"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "cd05f450-03cf-42fc-a56c-c96022946e84"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.4ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "soila_stracke@roberts.co"], ["encrypted_password", "$2a$04$TKxGhqnCOZO7cvbD0w2Qj.0TQRWagg2xmm6SxiSUwvobmLiidzjsO"], ["username", "amos"], ["created_at", "2020-05-17 22:54:21.696014"], ["updated_at", "2020-05-17 22:54:21.696014"], ["uid", "soila_stracke@roberts.co"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started POST "/api/v1/users/password" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::PasswordsController#create as JSON
  Parameters: {"email"=>"notvalid@example.com", "password"=>{"email"=>"notvalid@example.com"}}
[31mUnpermitted parameter: :password[0m
[31mUnpermitted parameter: :password[0m
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "notvalid@example.com"], ["provider", "email"], ["LIMIT", 1]]
Completed 404 Not Found in 2ms (Views: 0.1ms | ActiveRecord: 0.5ms | Allocations: 446)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.4ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "sona.simonis@yundttillman.io"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "976ee739-e99e-4553-a5db-681cd68fe844"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "sona.simonis@yundttillman.io"], ["encrypted_password", "$2a$04$UhN4hOCYkaSh1abOG/PYBOVIKxWa6ZK2nRlgi4zq4/V0NEWV0Qa5G"], ["username", "cecile.lynch"], ["created_at", "2020-05-17 22:54:21.720561"], ["updated_at", "2020-05-17 22:54:21.720561"], ["uid", "sona.simonis@yundttillman.io"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started POST "/api/v1/users/password" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::PasswordsController#create as JSON
  Parameters: {"email"=>"sona.simonis@yundttillman.io", "password"=>{"email"=>"sona.simonis@yundttillman.io"}}
[31mUnpermitted parameter: :password[0m
[31mUnpermitted parameter: :password[0m
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "sona.simonis@yundttillman.io"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["reset_password_token", "16bdc361908841488f6a0ecab677f368318a102762cf65ecfc7b203e54fb8e3e"], ["LIMIT", 1]]
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "reset_password_token" = $1, "reset_password_sent_at" = $2, "updated_at" = $3 WHERE "users"."id" = $4[0m  [["reset_password_token", "16bdc361908841488f6a0ecab677f368318a102762cf65ecfc7b203e54fb8e3e"], ["reset_password_sent_at", "2020-05-17 22:54:21.739745"], ["updated_at", "2020-05-17 22:54:21.739963"], ["id", 108]]
  [1m[35m (0.2ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  Rendering /Users/emerson/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.3/app/views/devise/mailer/reset_password_instructions.html.erb
  Rendered /Users/emerson/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.3/app/views/devise/mailer/reset_password_instructions.html.erb (Duration: 1.9ms | Allocations: 938)
Devise::Mailer#reset_password_instructions: processed outbound mail in 6.4ms
Delivered mail 5ec1c09db774d_17bab3fdf0c42e05c755f@Emersons-MacBook-Pro-2.local.mail (4.0ms)
Date: Sun, 17 May 2020 15:54:21 -0700
From: no-reply@api.com
Reply-To: no-reply@yourapi.com
To: sona.simonis@yundttillman.io
Message-ID: <5ec1c09db774d_17bab3fdf0c42e05c755f@Emersons-MacBook-Pro-2.local.mail>
Subject: Reset password instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
email: sona.simonis@yundttillman.io
provider: email
redirect-url: http://127.0.0.1:3000
client-config: default

<p>Hello sona.simonis@yundttillman.io!</p>

<p>Someone has requested a link to change your password. You can do this through the link below.</p>

<p><a href="http://localhost:3000/api/v1/users/password/edit?config=default&redirect_url=http%3A%2F%2F127.0.0.1%3A3000&reset_password_token=9zs8sdmjp1aKTQVizzzm">Change my password</a></p>

<p>If you didn&#39;t request this, please ignore this email.</p>
<p>Your password won&#39;t change until you access the link above and create a new one.</p>
Completed 200 OK in 18ms (Views: 0.2ms | ActiveRecord: 1.4ms | Allocations: 8513)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "jarred@daretrantow.net"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "581ce924-8eb2-467d-975c-523c33a8d4f7"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "jarred@daretrantow.net"], ["encrypted_password", "$2a$04$V16CYOrysMgjDC4hS57sjeaHFkAWQ3UGVtpjbZzNlVfQfZ1bx3J5W"], ["username", "wesley_keler"], ["created_at", "2020-05-17 22:54:21.760732"], ["updated_at", "2020-05-17 22:54:21.760732"], ["uid", "jarred@daretrantow.net"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started POST "/api/v1/users/password" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::PasswordsController#create as JSON
  Parameters: {"email"=>"jarred@daretrantow.net", "password"=>{"email"=>"jarred@daretrantow.net"}}
[31mUnpermitted parameter: :password[0m
[31mUnpermitted parameter: :password[0m
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "jarred@daretrantow.net"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["reset_password_token", "ebd59d0a76bc4b9c3a627334ce32fc872023e326946458835327b986b51d2df0"], ["LIMIT", 1]]
  [1m[35m (0.1ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "reset_password_token" = $1, "reset_password_sent_at" = $2, "updated_at" = $3 WHERE "users"."id" = $4[0m  [["reset_password_token", "ebd59d0a76bc4b9c3a627334ce32fc872023e326946458835327b986b51d2df0"], ["reset_password_sent_at", "2020-05-17 22:54:21.780671"], ["updated_at", "2020-05-17 22:54:21.780889"], ["id", 109]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  Rendering /Users/emerson/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.3/app/views/devise/mailer/reset_password_instructions.html.erb
  Rendered /Users/emerson/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.3/app/views/devise/mailer/reset_password_instructions.html.erb (Duration: 0.5ms | Allocations: 242)
Devise::Mailer#reset_password_instructions: processed outbound mail in 1.8ms
Delivered mail 5ec1c09dbf9ed_17bab3fdf0c42e05c76c5@Emersons-MacBook-Pro-2.local.mail (1.7ms)
Date: Sun, 17 May 2020 15:54:21 -0700
From: no-reply@api.com
Reply-To: no-reply@yourapi.com
To: jarred@daretrantow.net
Message-ID: <5ec1c09dbf9ed_17bab3fdf0c42e05c76c5@Emersons-MacBook-Pro-2.local.mail>
Subject: Reset password instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
email: jarred@daretrantow.net
provider: email
redirect-url: http://127.0.0.1:3000
client-config: default

<p>Hello jarred@daretrantow.net!</p>

<p>Someone has requested a link to change your password. You can do this through the link below.</p>

<p><a href="http://localhost:3000/api/v1/users/password/edit?config=default&redirect_url=http%3A%2F%2F127.0.0.1%3A3000&reset_password_token=nx86xU9RRUaGZguFAkWc">Change my password</a></p>

<p>If you didn&#39;t request this, please ignore this email.</p>
<p>Your password won&#39;t change until you access the link above and create a new one.</p>
Completed 200 OK in 8ms (Views: 0.1ms | ActiveRecord: 1.3ms | Allocations: 3975)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.2ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "sheba@pollich.name"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "689ea5e7-8dcf-4254-ad85-a16d7230cba5"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "sheba@pollich.name"], ["encrypted_password", "$2a$04$1BbM1D7Aqsq.fCp605yBjeDKctjrc3Ts7jXrfPmhWne1wxDzcBBgW"], ["username", "margaret"], ["created_at", "2020-05-17 22:54:21.793517"], ["updated_at", "2020-05-17 22:54:21.793517"], ["uid", "sheba@pollich.name"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started POST "/api/v1/users/password" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::PasswordsController#create as JSON
  Parameters: {"email"=>"sheba@pollich.name", "password"=>{"email"=>"sheba@pollich.name"}}
[31mUnpermitted parameter: :password[0m
[31mUnpermitted parameter: :password[0m
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "sheba@pollich.name"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["reset_password_token", "87a01649ad1686aad0896d9675114c8590a533fd06c808b3b3c6d512cfdba1cd"], ["LIMIT", 1]]
  [1m[35m (0.1ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "reset_password_token" = $1, "reset_password_sent_at" = $2, "updated_at" = $3 WHERE "users"."id" = $4[0m  [["reset_password_token", "87a01649ad1686aad0896d9675114c8590a533fd06c808b3b3c6d512cfdba1cd"], ["reset_password_sent_at", "2020-05-17 22:54:21.812953"], ["updated_at", "2020-05-17 22:54:21.813216"], ["id", 110]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  Rendering /Users/emerson/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.3/app/views/devise/mailer/reset_password_instructions.html.erb
  Rendered /Users/emerson/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.3/app/views/devise/mailer/reset_password_instructions.html.erb (Duration: 0.5ms | Allocations: 242)
Devise::Mailer#reset_password_instructions: processed outbound mail in 1.8ms
Delivered mail 5ec1c09dc7895_17bab3fdf0c42e05c77e0@Emersons-MacBook-Pro-2.local.mail (1.7ms)
Date: Sun, 17 May 2020 15:54:21 -0700
From: no-reply@api.com
Reply-To: no-reply@yourapi.com
To: sheba@pollich.name
Message-ID: <5ec1c09dc7895_17bab3fdf0c42e05c77e0@Emersons-MacBook-Pro-2.local.mail>
Subject: Reset password instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
email: sheba@pollich.name
provider: email
redirect-url: http://127.0.0.1:3000
client-config: default

<p>Hello sheba@pollich.name!</p>

<p>Someone has requested a link to change your password. You can do this through the link below.</p>

<p><a href="http://localhost:3000/api/v1/users/password/edit?config=default&redirect_url=http%3A%2F%2F127.0.0.1%3A3000&reset_password_token=xxsRfsbfRczD2vbMwGDu">Change my password</a></p>

<p>If you didn&#39;t request this, please ignore this email.</p>
<p>Your password won&#39;t change until you access the link above and create a new one.</p>
Completed 200 OK in 8ms (Views: 0.1ms | ActiveRecord: 1.2ms | Allocations: 3970)
  [1m[35m (0.3ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "kim@treutel.co"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Exists? (0.2ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["uid", "3928c95e-55d7-436e-ac5a-fbb89d1b29f1"], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Create (0.3ms)[0m  [1m[32mINSERT INTO "users" ("email", "encrypted_password", "username", "created_at", "updated_at", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["email", "kim@treutel.co"], ["encrypted_password", "$2a$04$viQ2AAZzm2ZbPddMICi75O56RWKhHKM6megnIU8OuNreuOh8trv1i"], ["username", "augustine_gulgowski"], ["created_at", "2020-05-17 22:54:21.825213"], ["updated_at", "2020-05-17 22:54:21.825213"], ["uid", "kim@treutel.co"]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["reset_password_token", "bfef103b2231e95e32947cbdded3efb8d058d8e6a6633b71f322dfa3fd9f2709"], ["LIMIT", 1]]
  [1m[35m (0.1ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "reset_password_token" = $1, "reset_password_sent_at" = $2, "updated_at" = $3 WHERE "users"."id" = $4[0m  [["reset_password_token", "bfef103b2231e95e32947cbdded3efb8d058d8e6a6633b71f322dfa3fd9f2709"], ["reset_password_sent_at", "2020-05-17 22:54:21.827181"], ["updated_at", "2020-05-17 22:54:21.827335"], ["id", 111]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Started GET "/api/v1/users/password/edit?reset_password_token=[FILTERED]&redirect_url=http%3A%2F%2F127.0.0.1%3A3000" for 127.0.0.1 at 2020-05-17 15:54:21 -0700
Processing by Api::V1::PasswordsController#edit as HTML
  Parameters: {"reset_password_token"=>"[FILTERED]", "redirect_url"=>"http://127.0.0.1:3000"}
[31mUnpermitted parameter: :redirect_url[0m
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["reset_password_token", "bfef103b2231e95e32947cbdded3efb8d058d8e6a6633b71f322dfa3fd9f2709"], ["LIMIT", 1]]
  [1m[35m (0.3ms)[0m  [1m[35mSAVEPOINT active_record_1[0m
  [1m[36mUser Exists? (0.3ms)[0m  [1m[34mSELECT 1 AS one FROM "users" WHERE "users"."uid" = $1 AND "users"."id" != $2 AND "users"."provider" = $3 LIMIT $4[0m  [["uid", "kim@treutel.co"], ["id", 111], ["provider", "email"], ["LIMIT", 1]]
  [1m[36mUser Update (0.3ms)[0m  [1m[33mUPDATE "users" SET "tokens" = $1, "allow_password_change" = $2, "updated_at" = $3 WHERE "users"."id" = $4[0m  [["tokens", "\"{\\\"zEYFWIhajxUmNmVIjN7WSg\\\":{\\\"token\\\":\\\"$2a$10$stbxCkrrhxbMamsX0yogKu0/jykljM4CPa8.b6S059mD0wVgVCEjO\\\",\\\"expiry\\\":1652828061}}\""], ["allow_password_change", true], ["updated_at", "2020-05-17 22:54:21.905018"], ["id", 111]]
  [1m[35m (0.1ms)[0m  [1m[35mRELEASE SAVEPOINT active_record_1[0m
Redirected to http://127.0.0.1:3000?access-token=ga9QDHg1LS8V84dDe5zSCw&client=zEYFWIhajxUmNmVIjN7WSg&client_id=zEYFWIhajxUmNmVIjN7WSg&config=&expiry=1652828061&reset_password=true&token=ga9QDHg1LS8V84dDe5zSCw&uid=kim%40treutel.co
Completed 302 Found in 62ms (ActiveRecord: 1.3ms | Allocations: 1551)
  [1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
```

### PR DESCRIPTION
**Pull request by emersonthis**
Fixes #205

### CODE REVIEW

File: app/controllers/api/v1/api_controller.rb [hunk 1]
```diff
@@ -5,6 +5,7 @@ class ApiController < ApplicationController
       include DeviseTokenAuth::Concerns::SetUserByToken
 
       before_action :authenticate_user!, except: :status
+      skip_after_action :verify_authorized, only: [:status]
```
Comment (fedeagripa) [inline app/controllers/api/v1/api_controller.rb:8]: just a small detail, no need for `[]` as you are specifying just one method

Comment (santib) [inline app/controllers/api/v1/api_controller.rb:8]:
```suggestion
      skip_after_action :verify_authorized, only: :status
```
